version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - to-do-network

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    ports:
      - 5000:8080
    restart: unless-stopped
    networks:
      - to-do-network

networks:
  to-do-network:
